server:
  port: ${PORT:8093}

spring:
  application:
    name: caju-transaction
  jackson:
    default-property-inclusion: non_null
    serialization:
      write_dates_as_timestamps: false
    property-naming-strategy: SNAKE_CASE
  messages:
    always-use-message-format: true
    basename: i18n/messages
    encoding: UTF-8
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
        web-allow-others: true
  sql:
    init:
      data-locations: classpath:import_account.sql
  datasource:
    url: jdbc:h2:mem:test;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    platform: h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: H2
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
external:
  merchant:
    host: http://localhost:8080